-- ---------------------------------------------------------------------
-- seed ingredients from bahan_kategori.tsv
-- Mapping: KODE -> id, NAMA BAHAN -> name, KATEGORI -> category, HARGA -> price
-- ---------------------------------------------------------------------

INSERT INTO ingredients (id, name, category, price, image_url)
SELECT 
    v.id, v.name, v.category, v.price,
    (ARRAY[
        'https://unsplash.com/photos/a-single-carrot-on-a-white-background-eJJ2316gOak',
        'https://unsplash.com/photos/sliced-tomato-on-white-surface-sgmS2e95QO0',
        'https://unsplash.com/photos/red-chili-on-white-background-nZUQgW0FVnc',
        'https://unsplash.com/photos/raw-meat-on-brown-wooden-table-QH8SHBARVVk',
        'https://unsplash.com/photos/pile-of-gray-fishes-vLQzopDRSNI'
    ])[1 + floor(random() * 5)::int]
FROM (VALUES 
    ('AR014', 'Cantel/Sorgum, mentah', 'Serealia', 'murah'),
    ('GR048', 'Ikan mujahir, segar', 'Hewan Air Tawar', 'sedang'),
    ('FR016', 'Daging Domba, segar', 'Mamalia', 'mahal'),
    ('FR012', 'Daging Bebek, segar', 'Unggas', 'mahal'),
    ('ER031', 'Jambu biji', 'Buah', 'murah'),
    ('DR154', 'Terong, segar', 'Sayur', 'murah'),
    ('GR011', 'Ikan baung, segar', 'Hewan Air Tawar', 'sedang'),
    ('GR012', 'Ikan bawal, segar', 'Hewan Laut', 'mahal'),
    ('GR019', 'Ikan cakalang, segar', 'Hewan Laut', 'mahal'),
    ('GR057', 'Ikan sarden, segar', 'Hewan Laut', 'mahal'),
    ('KP003', 'Santan (dengan air)', 'Minyak/Lemak', 'sedang'),
    ('JR006', 'Susu sapi, segar', 'Susu/Olahan Susu', 'sedang'),
    ('JR003', 'Susu kambing, segar', 'Susu/Olahan Susu', 'mahal'),
    ('BR031', 'Ubi jalar putih, segar', 'Umbi', 'murah'),
    ('BR028', 'Ubi jalar, kuning, segar', 'Umbi', 'murah'),
    ('BR030', 'Ubi jalar merah, segar', 'Umbi', 'murah'),
    ('BR016', 'Ketela pohon/ singkong, segar', 'Umbi', 'murah'),
    ('BR013', 'Kentang, segar', 'Umbi', 'murah'),
    ('AR001', 'Beras giling, mentah', 'Serealia', 'murah'),
    ('AR013', 'Beras tumbuk merah, mentah', 'Serealia', 'murah'),
    ('AR004', 'Beras hitam, mentah', 'Serealia', 'murah'),
    ('AR005', 'Beras jagung kuning, kering, mentah', 'Serealia', 'murah'),
    ('AR008', 'Beras ketan putih tumbuk, mentah', 'Serealia', 'murah'),
    ('GR053', 'Ikan patin, segar', 'Hewan Air Tawar', 'sedang'),
    ('GR046', 'Ikan mas, segar', 'Hewan Air Tawar', 'sedang'),
    ('GR025', 'Ikan gabus, segar', 'Hewan Air Tawar', 'sedang'),
    ('GR001', 'Belut, segar', 'Hewan Air Tawar', 'mahal'),
    ('GR082', 'Udang galah, segar', 'Hewan Laut', 'mahal'),
    ('GR003', 'Cumi-cumi, segar', 'Hewan Laut', 'mahal'),
    ('GR068', 'Ikan teri, segar', 'Hewan Laut', 'murah'),
    ('FR005', 'Daging Ayam, segar', 'Unggas', 'murah'),
    ('FR007', 'Hati Ayam,  segar', 'Unggas', 'murah'),
    ('HR001', 'Telur ayam kampung, segar', 'Unggas', 'murah'),
    ('HR002', 'Telur ayam ras, segar', 'Unggas', 'murah'),
    ('HR005', 'Telur bebek alabio, segar', 'Unggas', 'sedang'),
    ('FR024', 'Daging Sapi, segar', 'Mamalia', 'mahal'),
    ('FR019', 'Daging Kambing, segar', 'Mamalia', 'mahal'),
    ('FR031', 'Hati Sapi, segar', 'Mamalia', 'sedang'),
    ('CR017', 'Kacang kedelai, kering', 'Kacang/Biji', 'sedang'),
    ('CR032', 'Kacang tanah, kering', 'Kacang/Biji', 'sedang'),
    ('CR014', 'Kacang hijau, kering', 'Kacang/Biji', 'murah'),
    ('CR026', 'Kacang merah, kering', 'Kacang/Biji', 'murah'),
    ('CR035', 'Kacang uci, kering', 'Kacang/Biji', 'murah'),
    ('CP077', 'Tempe kedelai murni, mentah', 'Kacang/Biji (Olahan)', 'murah'),
    ('CP061', 'Tahu, mentah', 'Kacang/Biji (Olahan)', 'murah'),
    ('KR011', 'Minyak kelapa', 'Minyak/Lemak', 'murah'),
    ('KR014', 'Minyak zaitun', 'Minyak/Lemak', 'mahal'),
    ('KR013', 'Minyak wijen', 'Minyak/Lemak', 'sedang'),
    ('ER073', 'Pepaya, segar', 'Buah', 'murah'),
    ('ER054', 'Mangga, segar', 'Buah', 'murah'),
    ('ER070', 'Nanas, segar', 'Buah', 'murah'),
    ('ER087', 'Pisang mas, segar', 'Buah', 'murah'),
    ('ER001', 'Alpukat, segar', 'Buah', 'mahal'),
    ('ER071', 'Nangka masak pohon, segar', 'Buah', 'murah'),
    ('ER035', 'Jeruk bali, segar', 'Buah', 'mahal'),
    ('ER039', 'Jeruk manis, segar', 'Buah', 'murah'),
    ('ER104', 'Sawo Manila, segar', 'Buah', 'murah'),
    ('ER106', 'Sirsak, segar', 'Buah', 'murah'),
    ('ER065', 'Markisa, segar', 'Buah', 'sedang'),
    ('ER097', 'Rambutan, segar', 'Buah', 'murah'),
    ('ER101', 'Salak, segar', 'Buah', 'murah'),
    ('ER012', 'Buah Naga Merah, segar', 'Buah', 'sedang'),
    ('ER052', 'Lemon, segar', 'Buah', 'mahal'),
    ('ER064', 'Manggis, segar', 'Buah', 'sedang'),
    ('ER003', 'Apel malang, segar', 'Buah', 'sedang'),
    ('DR038', 'Daun kelor, segar', 'Sayur', 'murah'),
    ('DR071', 'Daun singkong, segar', 'Sayur', 'murah'),
    ('DR008', 'Bayam, segar', 'Sayur', 'murah'),
    ('DR044', 'Daun kubis, segar', 'Sayur', 'murah'),
    ('DR141', 'Sawi, segar', 'Sayur', 'murah'),
    ('DR123', 'Labu siam, segar', 'Sayur', 'murah'),
    ('DR161', 'Tomat merah, segar', 'Sayur', 'murah'),
    ('DR166', 'Wortel, segar', 'Sayur', 'murah'),
    ('DR097', 'Kacang panjang, segar', 'Sayur', 'murah'),
    ('DR013', 'Buncis, segar', 'Sayur', 'murah'),
    ('DR113', 'Kool kembang', 'Sayur', 'murah')
) AS v(id, name, category, price)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    category   = EXCLUDED.category,
    price      = EXCLUDED.price,
    image_url  = EXCLUDED.image_url,
    updated_at = now();
